name: Print Secrets
on:
  workflow_dispatch:

jobs:
  print_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          if [[ "${{ secrets.NAME }}" == *Rohit* ]]; then
            echo "Yes"
          else
            echo "No"
          fi
        env:
          MY_SECRET: ${{ secrets.NAME }}
